FROM arm32v7/python:3.11-slim-buster

WORKDIR /app

COPY led.py .

RUN apt-get update && \
    apt-get install -y build-essential && \
    pip install --no-cache-dir rpi.gpio && \
    apt-get remove -y build-essential && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

CMD ["python", "./led.py"]